### ISSUE TITLE
Idea Details Page

### ISSUE THREAD

**Issue by DanielQuick** [DanielQuick/Flutter-Sprints-Idea-Tracker#17]
- [x] App bar
- [x] Idea Title
- [x] Idea Description
- [x] Edit Button (only if user owns the idea)

**Comment by labody** [comment]
> * [x]  App bar
> * [x]  Idea Title
> * [x]  Idea Description

> > * [ ]  Edit Button (only if user owns the idea)
How do we determine if the user owns the idea? Is it by the matching of the <b>user id</b> and the <b>idea id</b> ??

**Comment by taracell** [comment]
We can add a user if field to the idea and I can connect the user id to it through firebase. Then all you have to do is call the office create and the user id should be already in there. On update there are 2 ways to do that. 1.  You match the user I'd in the screen to show the update button if not it returns an empty container instead of the button or the button doesn't work because of programming in the update service from firestore. Let me know what you want so I can edit.

**Comment by labody** [comment]
> We can add a user if field to the idea and I can connect the user id to it through firebase. Then all you have to do is call the office create and the user id should be already in there. On update there are 2 ways to do that. 1.  You match the user I'd in the screen to show the update button if not it returns an empty container instead of the button or the button doesn't work because of programming in the update service from firestore. Let me know what you want so I can edit. 

I'm slowly understanding what you are saying as I get the first part and the last part but what I don't get is the office create part. I've looked through the code and I can't find a function called that. About to sleep, would reread this again tomorrow for more understanding.

**Comment by taracell** [comment]
> > We can add a user if field to the idea and I can connect the user id to it through firebase. Then all you have to do is call the office create and the user id should be already in there. On update there are 2 ways to do that. 1.  You match the user I'd in the screen to show the update button if not it returns an empty container instead of the button or the button doesn't work because of programming in the update service from firestore. Let me know what you want so I can edit.
> 
> I'm slowly understanding what you are saying as I get the first part and the last part but what I don't get is the office create part. I've looked through the code and I can't find a function called that. About to sleep, would reread this again tomorrow for more understanding.

office should say idea...Sorry
Option 1: what I was saying above was to create a widget like the one below to call to your widget tree, the button would only show up if the id of the current logged in user matches the userId stored in the idea when the idea was created.  

I will add that to the model and make it part of the idea object so who is logged in and creates an idea within the application will be connected to that idea via their user id.

Option 2:
From the backend, if the logged-in user does not match the user id within the idea object it will not update and will return a string saying "if you are not the creator of this idea, you cannot update it".

Your button can persist on the page with option 2 but the user will go through the trouble of editing the idea and when they hit update or edit or whatever, they will get the message.

```dart
///pass the user id of the current user into the widget
  getIconButton(String userId) {
    if (userId == idea.userId) {       
          new IconButton(icon: Icon(Icons.create),
            onPressed: () {
             ///TODO:  code to make textfield editable
            },
          );
    } else {
      return new Container();
    } //else
  }
```

**Comment by labody** [comment]
Wow. This is a great learning experience for me and you've broken things down so well for me to digest them easily. Thanks for the help. 

I think Option 1 would be better as the one who created idea should be the only one to edit the Idea. So there is no need for other users to see the edit button if they won't be able to use it.

I'll try it and get back to you.

**Comment by labody** [comment]
> > > We can add a user if field to the idea and I can connect the user id to it through firebase. Then all you have to do is call the office create and the user id should be already in there. On update there are 2 ways to do that. 1.  You match the user I'd in the screen to show the update button if not it returns an empty container instead of the button or the button doesn't work because of programming in the update service from firestore. Let me know what you want so I can edit.
> > 
> > 
> > I'm slowly understanding what you are saying as I get the first part and the last part but what I don't get is the office create part. I've looked through the code and I can't find a function called that. About to sleep, would reread this again tomorrow for more understanding.
> 
> office should say idea...Sorry
> Option 1: what I was saying above was to create a widget like the one below to call to your widget tree, the button would only show up if the id of the current logged in user matches the userId stored in the idea when the idea was created.
> 
> I will add that to the model and make it part of the idea object so who is logged in and creates an idea within the application will be connected to that idea via their user id.
> 
> Option 2:
> From the backend, if the logged-in user does not match the user id within the idea object it will not update and will return a string saying "if you are not the creator of this idea, you cannot update it".
> 
> Your button can persist on the page with option 2 but the user will go through the trouble of editing the idea and when they hit update or edit or whatever, they will get the message.
> 
> ```dart
> ///pass the user id of the current user into the widget
>   getIconButton(String userId) {
>     if (userId == idea.userId) {       
>           new IconButton(icon: Icon(Icons.create),
>             onPressed: () {
>              ///TODO:  code to make textfield editable
>             },
>           );
>     } else {
>       return new Container();
>     } //else
>   }
> ```

Wow. This is a great learning experience for me and you've broken things down so well for me to digest them easily. Thanks for the help.

I think Option 1 would be better as the one who created idea should be the only one to edit the Idea. So there is no need for other users to see the edit button if they won't be able to use it.

I'll try it and get back to you.

**Comment by labody** [comment]
``` dart
Widget getEditButton(String userId) {
    if (userId == idea.userId) {
      return IconButton(
        icon: Icon(Icons.edit),
        onPressed: () {},
      );
    } else {
      return SizedBox.shrink();
    }
  }
```

This displays the edit Button @taracell
