### ISSUE TITLE
Idea Service Enhancement

### ISSUE THREAD

**Issue by DanielQuick** [DanielQuick/Flutter-Sprints-Idea-Tracker#29]
- [x] Vote for idea
- [x] Unvote for idea
- [x] Get number of votes

**Comment by taracell** [comment]
To do this I need to change the vote property of the Idea object within models.  Is this acceptable?

**Comment by taracell** [comment]
Adding/deleting voters from voter's list within an Idea object and getting the length of the list should accomplish this task
